esphome:
  name: matrix-display
  friendly_name: Matrix Display


external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main

esp32:
  board: esp32dev
  framework:
    type: arduino

color:
  - id: purple
    red: 100%
    green: 0%
    blue: 100%

font:
  # gfonts://family[@weight]
  - file: "gfonts://Open Sans"
    id: roboto
    size: 10

http_request:
  verify_ssl: False

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    R1_pin: 25
    G1_pin: 26
    B1_pin: 27
    R2_pin: 14
    G2_pin: 12
    B2_pin: 13
    A_pin: 23
    B_pin: 22
    C_pin: 5
    D_pin: 17
    E_pin: 32
    LAT_pin: 4
    OE_pin: 15
    CLK_pin: 16

    lambda: |-
      it.fill(Color::BLACK);
      it.print(0, 0, id(roboto), Color(id(purple)), "Living room:");
      it.printf(0, 16, id(roboto), Color(id(purple)), "%.1f°C", id(temperature).state);

sensor:
  - id: temperature
    platform: homeassistant
    entity_id: sensor.living_room_temp_humidity_temperature
    accuracy_decimals: 1
    on_value:
      - component.update: matrix


switch:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Power"
    id: power

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Brightness"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dB # added to counteract interference from the display

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Matrix-Display Fallback Hotspot"
    password: "x"

captive_portal:
    